name: CI CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: cmake generate
      run: cmake .
    - name: cmake build
      run: cmake --build .
